/** 홈 화면 전용 색상 토큰과 레이아웃 스타일이다. */
import { StyleSheet } from 'react-native';

export const HOME_COLORS = {
  primary: '#00B4C8',
  white: '#FFFFFF',
  black: '#111111',
  textDark: '#222222',
  textDefault: '#333333',
  textSub: '#555555',
  textMuted: '#666666',
  placeholder: '#AAAAAA',
  cardBg: '#F0F4F8',
  dangerBg: '#FFF1F1',
  dangerBorder: '#FFB8B8',
  danger: '#E84646',
  warningBg: '#FFF5D8',
  warningText: '#7A4A00',
  registeredBg: '#FFF3BD',
  registeredIcon: '#B47C00',
  modalBackdrop: 'rgba(0, 0, 0, 0.36)',
  logoBg: '#F0F0F0',
  inputBorder: '#222222',
};

const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: HOME_COLORS.white,
  },

  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 64,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: HOME_COLORS.white,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
  },
  logoCircle: {
    width: 40,
    height: 40,
    marginRight: 10,
    borderRadius: 20,
    backgroundColor: HOME_COLORS.logoBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoText: {
    fontSize: 20,
  },
  headerTitle: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    color: HOME_COLORS.textDark,
  },
  headerSubtitle: {
    fontSize: 12,
    lineHeight: 16,
    color: HOME_COLORS.textSub,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
  },
  iconBtn: {
    width: 34,
    height: 34,
    marginLeft: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },

  scrollView: {
    flex: 1,
    backgroundColor: HOME_COLORS.white,
  },
  scrollContent: {
    paddingBottom: 20,
  },

  hero: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
  },
  heroContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  heroTextBlock: {
    flex: 1,
  },
  heroText: {
    marginBottom: 4,
    fontSize: 16,
    color: HOME_COLORS.textDefault,
  },
  heroBold: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '800',
    color: HOME_COLORS.black,
  },
  heroBalloon: {
    width: 90,
    height: 90,
    marginLeft: 12,
    borderRadius: 45,
    backgroundColor: HOME_COLORS.cardBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  balloonEmoji: {
    fontSize: 50,
  },

  chatInputWrapper: {
    paddingHorizontal: 20,
    marginBottom: 18,
  },
  chatInputBox: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 16,
    paddingRight: 6,
    borderWidth: 1.5,
    borderColor: HOME_COLORS.inputBorder,
    borderRadius: 25,
    backgroundColor: HOME_COLORS.white,
  },
  chatInputIcon: {
    marginRight: 8,
  },
  chatTextInput: {
    flex: 1,
    paddingVertical: 0,
    fontSize: 14,
    color: HOME_COLORS.textDefault,
  },
  clearInputButton: {
    marginLeft: 8,
  },
  chatSubmitButton: {
    width: 38,
    height: 38,
    marginLeft: 8,
    borderRadius: 19,
    backgroundColor: HOME_COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },

  cardsSection: {
    paddingHorizontal: 16,
    marginBottom: 20,
  },
  cardLarge: {
    minHeight: 120,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    padding: 20,
    borderRadius: 16,
    backgroundColor: HOME_COLORS.cardBg,
  },
  cardTextBlock: {
    flex: 1,
  },
  cardTitle: {
    marginBottom: 6,
    fontSize: 16,
    fontWeight: '700',
    color: HOME_COLORS.black,
  },
  cardDesc: {
    fontSize: 13,
    lineHeight: 19,
    color: HOME_COLORS.textSub,
  },
  cardIconWrap: {
    marginLeft: 12,
  },
  cardIconBg: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: HOME_COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardIconEmoji: {
    fontSize: 36,
  },
  cardRow: {
    flexDirection: 'row',
  },
  cardSmall: {
    flex: 1,
    minHeight: 110,
    padding: 18,
    borderRadius: 16,
    backgroundColor: HOME_COLORS.cardBg,
    justifyContent: 'space-between',
  },
  cardSmallSpacing: {
    marginRight: 10,
  },
  cardSmallTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '700',
    color: HOME_COLORS.black,
  },
  cardSmallEmoji: {
    marginTop: 8,
    fontSize: 36,
    alignSelf: 'flex-end',
  },

  profileSectionWrapper: {
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  profileWarningBubble: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingLeft: 14,
    paddingRight: 8,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: HOME_COLORS.warningBg,
  },
  profileWarningText: {
    flex: 1,
    marginRight: 8,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '700',
    color: HOME_COLORS.warningText,
  },
  warningCloseButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileSection: {
    minHeight: 92,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: HOME_COLORS.white,
  },
  profileSectionUnregistered: {
    borderWidth: 1,
    borderColor: HOME_COLORS.dangerBorder,
    backgroundColor: HOME_COLORS.dangerBg,
  },
  profileSectionTextBlock: {
    flex: 1,
    paddingRight: 14,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  profileTitle: {
    marginRight: 4,
    fontSize: 16,
    fontWeight: '700',
    color: HOME_COLORS.black,
  },
  profileDesc: {
    fontSize: 13,
    lineHeight: 20,
    color: HOME_COLORS.textMuted,
  },
  profileStatusBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileStatusBadgeRegistered: {
    backgroundColor: HOME_COLORS.registeredBg,
  },
  profileStatusBadgeUnregistered: {
    backgroundColor: HOME_COLORS.danger,
  },

  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 22,
    backgroundColor: HOME_COLORS.modalBackdrop,
  },
  profileModal: {
    width: '100%',
    maxHeight: '88%',
    padding: 20,
    borderRadius: 18,
    backgroundColor: HOME_COLORS.white,
  },
  profileModalScroll: {
    flexShrink: 1,
  },
  profileModalContent: {
    paddingBottom: 10,
  },
  modalTitle: {
    marginBottom: 18,
    fontSize: 19,
    lineHeight: 25,
    fontWeight: '800',
    color: HOME_COLORS.black,
    textAlign: 'center',
  },
  formGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    marginBottom: 7,
    fontSize: 13,
    fontWeight: '700',
    color: HOME_COLORS.textDefault,
  },
  modalInput: {
    minHeight: 46,
    paddingHorizontal: 13,
    borderWidth: 1,
    borderColor: '#D8E0E6',
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    fontSize: 14,
    color: HOME_COLORS.textDefault,
  },
  genderTrack: {
    height: 46,
    flexDirection: 'row',
    position: 'relative',
    overflow: 'hidden',
    padding: 3,
    borderRadius: 23,
    backgroundColor: '#E9EEF2',
  },
  genderThumb: {
    position: 'absolute',
    top: 3,
    left: 3,
    bottom: 3,
    width: '50%',
    borderRadius: 20,
    backgroundColor: HOME_COLORS.white,
    boxShadow: '0 2px 6px rgba(0, 0, 0, 0.16)',
  },
  genderOption: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  genderOptionText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#7A858C',
  },
  genderOptionTextActive: {
    color: HOME_COLORS.black,
  },
  privacyConsentSection: {
    marginTop: 2,
    marginBottom: 12,
  },
  privacyConsentAllRow: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
  },
  privacyConsentAllButton: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
  },
  privacyConsentAllText: {
    marginLeft: 7,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '800',
    color: HOME_COLORS.textDefault,
  },
  privacyConsentError: {
    flex: 1,
    marginLeft: 8,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '700',
    color: HOME_COLORS.danger,
    textAlign: 'right',
  },
  privacyConsentDivider: {
    height: StyleSheet.hairlineWidth,
    marginTop: 7,
    marginBottom: 7,
    backgroundColor: '#DDE5EA',
  },
  privacyConsentItem: {
    paddingVertical: 3,
  },
  privacyConsentRow: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  privacyConsentCheckButton: {
    width: 28,
    minHeight: 34,
    paddingTop: 2,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  privacyConsentTextButton: {
    minHeight: 34,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingTop: 4,
    paddingRight: 6,
  },
  privacyConsentTitle: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    color: HOME_COLORS.textDefault,
  },
  privacyConsentRequired: {
    marginLeft: 5,
    fontSize: 11,
    lineHeight: 18,
    fontWeight: '700',
    color: '#A7B0B7',
  },
  privacyConsentChevronButton: {
    width: 32,
    minHeight: 34,
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    paddingTop: 3,
  },
  privacyConsentDescription: {
    marginLeft: 28,
    paddingRight: 32,
    paddingBottom: 5,
    fontSize: 11,
    lineHeight: 17,
    color: HOME_COLORS.textMuted,
  },
  modalButtonRow: {
    flexDirection: 'row',
    marginTop: 8,
  },
  modalButton: {
    flex: 1,
    height: 46,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelButton: {
    marginRight: 8,
    backgroundColor: '#EEF2F5',
  },
  submitButton: {
    marginLeft: 8,
    backgroundColor: HOME_COLORS.primary,
  },
  submitButtonDisabled: {
    opacity: 0.65,
  },
  cancelButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: HOME_COLORS.textDefault,
  },
  submitButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: HOME_COLORS.white,
  },

  floatingBtn: {
    // bottom 위치는 기기 safe area와 커스텀 탭바 높이를 반영해 HomeScreen에서 계산한다.
    position: 'absolute',
    right: 16,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: HOME_COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.25)',
  },
  floatingBtnText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '700',
    color: HOME_COLORS.white,
    textAlign: 'center',
  },
});

export default homeStyles;
